### ISSUE TITLE
Problems migrating from EasyRpc 3.0.1 to 5.0

### ISSUE THREAD

**Issue by todaysoftware** [ipjohnson/EasyRpc#116]
Trying to migrate a project from .NET Core 2.2 to .NET 5 but cannot get the EasyRpc API working.  

Under 3.0 we setup the API endpoint using
```
var serviceName = "/Plugins/Misc.MyInterface/MyInterface";
app.UseJsonRpc(serviceName, api =>
{
    api.Expose<MyInterfaceJsonRpc>();
});
```
And we can reach the API via the serviceName (https://../Plugins/Misc.MyInterface/MyInterface/)

User 5.0 we don't seem to be able to specify an endpoint that I could find so we have the following
```
app.UseRpcRouting(api =>
{
    api.Environment.Documentation(docs => docs.RedirectRootToDocumentation = false);
    api.Expose<MyInterfaceJsonRpc>();
});
```

But now I have no idea where the endpoint is, I have tried accessing it via /MyInterfaceJsonRpc with no success.  I tried adding .As(ServiceName) to the api.Expose but still cannot find it where I expect and tried all sorts of variations all with no success.

I have spent hours searching source code, wiki's, issues, internet etc but have go nowhere so assistance would be very appreciated.

**Comment by ipjohnson** [comment]
Hi @todaysoftware 

The big difference for version 5 is that I removed the json rpc wrapper around the payload to support different serializes (specifically message pack) as well as to support more common usage (I converted a number of services for my former employer to standard REST).

You can possible stay on version 3 and upgrade to .net 5.0 if you set the `AllowSynchronousIO = true` for your setup which will allow EasyRpc to serialize without having to do async. 

In 5.0 you can set the base path like so

```
api.Environment.BasePath("/Plugins/Misc.MyInterface");
```

If you set the document redirect flag to try and then navigate with a browser to the `/` what do you see exposed?

**Comment by todaysoftware** [comment]
Hi @ipjohnson , thanks for the response - much appreciated.

Adding the BasePath helped a bit, I removed the RedirectRootToDocumentation and can now navigate to /Plugins/Misc.MyInterface/ which then redirects to /Plugins/Misc.MyInterface/swagger/index.html but that just gives me a blank page.  So seems a bit like I haven't managed to register the class properly.

I will take a look at the possibility of using V3, although the underlying project has gone all async in this version so need to use async if we can. 

Just to add some context we are using an open source ecommerce platform (nopcommerce) and we have a plugin that allows us to exchange data with internal retail systems for orders and products, pricing, etc.  Was originally a SOAP service but had major problems trying to make that work with .NET core 2 which is why we changed it to use JSON-RPC to exchange data - and it has worked extremely well for the last 18 months :+1:

**Comment by ipjohnson** [comment]
I'm not sure that supporting json-rpc with 5.0 is going to be as easy as I originally thought. That said before I made the change to jettison json-rpc I made a version that supports both asp.net 3.0 and json-rpc. 

https://github.com/ipjohnson/EasyRpc/tree/4.0

I don't have time to maintain multiple code lines but I'd be willing to let you fork it under a different name (any license you'd like).

**Comment by todaysoftware** [comment]
OK no problem.  Right now I have it working using the 3.0 assembly and AllowSynchronousIO = true.  I will take a look at 4.0 later on this week, but seems like we will have a solution either way.

Many thanks for taking your time to respond!

**Comment by ipjohnson** [comment]
Out of curiosity what did you end up doing?

**Comment by todaysoftware** [comment]
Using the 4.0 version and so far seems to be working well!

**Comment by todaysoftware** [comment]
We still had to have the AllowSynchronousIO enabled with version 4.0 for it to work but we have been chasing a different problem and it was suggested that this flag might be contributing to the problem.  So I have managed make some changes so that it now works without that flag.

I know you are not going to maintain multiple versions but happy to send through a pull request if you want me to.

 https://github.com/todaysoftware/EasyRpc/commit/75a251aaa81e3ecfd5651389f9ce8c77076cf739

**Comment by ipjohnson** [comment]
That looks good, if you send a PR I'll look to release it this weekend.
